<a href="https://colab.research.google.com/github/Aashnajaiaswal0510/Data_Science_NF/blob/main/Data_Cleaning_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Employment of India Dataset - Data Cleaning Project

In [ ]:
#Here we will import our dataset csv file
from google.colab import files
uploaded = files.upload()

Saving Messy_Employment_India_Dataset.csv to Messy_Employment_India_Dataset.csv

# Step 1: Load and Inspect Dataset

In this step, we import the required libraries and load the dataset.

In [ ]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("Messy_Employment_India_Dataset.csv")

# Display first 5 rows to see first few rows to check what data is available
df.head()

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023

# Step 2: Understand Dataset Structure

We will check the shape, columns, and data types of the dataset.
This will help us to identify which columns need cleaning.

In [ ]:
# Shape of dataset
print("Rows and Columns:", df.shape)

# Column names
print(df.columns)

# Data types
df.info()

# Statistical summary
df.describe(include="all")

Rows and Columns: (2000, 9)
Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years of Experience', 'Monthly Salary (INR)', 'Date Recorded'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   object
dtypes: float64(2), object(7)
memory usage: 140.8+ KB

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
count,1732,1768,1804,1799,1787,1716,980.000000,1613.000000,2000
unique,6,7,9,8,8,6,NaN,NaN,2000
top,Employed,18 to 24,Bachelors,Retail,Delhi,HIGH,NaN,NaN,6/6/2028
freq,302,262,225,429,233,308,NaN,NaN,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,15.244898,76886.360818,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,9.103941,41628.008054,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,5100.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,40700.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,16.000000,77200.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,23.000000,112400.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,149900.000000,NaN

# Step 3: Handle Missing Values

Missing values can affect analysis and machine learning models.
We replace missing values with the mode and numerical values with the median.

In [ ]:
# Check missing values
df.isnull().sum()

Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64

# Step 4: Remove Duplicate Records

Duplicate rows can distort analysis.
We identify and remove duplicate records.

In [ ]:
print("Duplicates:", df.duplicated().sum())

df = df.drop_duplicates()

print("After Removal:", df.duplicated().sum())

Duplicates: 0
After Removal: 0

# Step 5: Correct Inconsistent Formatting

Text values contain inconsistent capitalization and spacing.
We standardize them for consistency.

# Step 6: Fix Data Types

We convert columns to appropriate data types.

In [ ]:
df['Date Recorded'] = pd.to_datetime(
    df['Date Recorded']
)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                2000 non-null   object
 1   Age Group             2000 non-null   object
 2   Education             2000 non-null   object
 3   Industry              2000 non-null   object
 4   Location              2000 non-null   object
 5   AI Risk               2000 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 140.8+ KB

# Step 7: Detect and Handle Outliers

Outliers are extreme values that can affect analysis.
We use the IQR method.

# Step 8: Standardize Column Names

Column names should follow a consistent format.

In [ ]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "")
    .str.replace(")", "")
)

df.columns

Index(['status', 'age_group', 'education', 'industry', 'location', 'ai_risk',
       'years_of_experience', 'monthly_salary_inr', 'date_recorded'],
      dtype='object')

# Step 9: Validate Cleaned Data

We verify that the dataset is clean and ready for analysis.

In [ ]:
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicates:")
print(df.duplicated().sum())

df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 1613 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   status               1613 non-null   object
 1   age_group            1613 non-null   object
 2   education            1613 non-null   object
 3   industry             1613 non-null   object
 4   location             1613 non-null   object
 5   ai_risk              1613 non-null   object
 6   years_of_experience  812 non-null    float64
 7   monthly_salary_inr   1613 non-null   float64
 8   date_recorded        1613 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 126.0+ KB
None

Missing Values:
status                   0
age_group                0
education                0
industry                 0
location                 0
ai_risk                  0
years_of_experience    801
monthly_salary_inr       0
date_recorded            0
dtype: int64

Duplicates:
0

,status,age_group,education,industry,location,ai_risk,years_of_experience,monthly_salary_inr,date_recorded
0,Employed,25_34,High School,Technology,Urban,High,NaN,40700.0,2023-01-01
1,Employed,18-24,Diploma,Finance,rural,Moderate,NaN,17500.0,2023-01-02
2,Employed,25_34,High School,Retail,Delhi,Low,16.0,77600.0,2023-01-03
3,Unemployed,18-24,Masters,Retail,Urban,Low,30.0,100200.0,2023-01-04
4,Employed,45-54,Diploma,Finance,Hyderabad,Low,9.0,19500.0,2023-01-05

# Step 10: Export Cleaned Dataset

The cleaned dataset is exported for future analysis.

In [ ]:
df.to_csv(
    "Cleaned_Employment_India_Dataset.csv",
    index=False
)

print("Dataset Exported Successfully")

Dataset Exported Successfully

# Conclusion

The dataset was successfully cleaned by handling missing values,
removing duplicates, standardizing text values ,
correcting data types, treating outliers ,
and exporting a clean version for analysis.