<a href="https://colab.research.google.com/github/Aashnajaiaswal0510/Data_Science_NF/blob/main/Module_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Data Frame

In [ ]:
import pandas as pd
list=[2,4,6,8,10]
df= pd.DataFrame(list)
print(df)
print(type(df))

    0
0   2
1   4
2   6
3   8
4  10
<class 'pandas.core.frame.DataFrame'>

In [ ]:
#use of dict in df
info= {
    "name": "aashna",
    "age": 19,
    "city": "delhi",
    "marks":98

}
df=pd.DataFrame(info , index=["a","b","c"])
print(df)

     name  age   city  marks
a  aashna   19  delhi     98
b  aashna   19  delhi     98
c  aashna   19  delhi     98

In [ ]:

info= {
    "name=": ["aashna","shabnam","sunaina"],
    "age": [19,20,18],
    "city": ["delhi","noida","up"],
    "marks":[98,56,78]

}
df=pd.DataFrame(info,index=["a","b","c"] )

print(df)

     name=  age   city  marks
a   aashna   19  delhi     98
b  shabnam   20  noida     56
c  sunaina   18     up     78

In [ ]:
info= {
    "name=": ["aashna","shabnam","sunaina"],
    "age": [19,20,18],
    "city": ["delhi","noida","up"],
    "marks":[98,56,78]

}
df=pd.DataFrame(info,columns=["name","age"] )

print(df)

  name  age
0  NaN   19
1  NaN   20
2  NaN   18

In [ ]:
info= {
    "name=": ["aashna","shabnam","sunaina"],
    "age": [19,20,18],
    "city": ["delhi","noida","up"],
    "marks":[98,56,78]

}
df=pd.DataFrame(info,columns=["name","age"] )

print(df)

In [ ]:
#nested list in df
list1=[["a","b"],["A","B"]]
df= pd.DataFrame(list1)
print(df)

   0  1
0  a  b
1  A  B

In [ ]:
#dict
sr={
    "s":pd.Series([1,2,3,4]),
    "r":pd.Series([5,6,7,8])
}
df=pd.DataFrame(sr)
# print(df)
df

   s  r
0  1  5
1  2  6
2  3  7
3  4  8

In [ ]:
df=pd.DataFrame({
    "a":[1,2,3,4],
    "b":[5,6,7,8]
})
df["c"]=df["a"]+df["b"]
df

   a  b   c
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [ ]:
df=pd.DataFrame({
    "a":[1,2,3,4],
    "b":[5,6,7,8]
})
df["c"]=df["a"]+df["b"]
df["try"]=df["a"]>5
df["try2"]=df["c"]>1
df

   a  b   c    try  try2
0  1  5   6  False  True
1  2  6   8  False  True
2  3  7  10  False  True
3  4  8  12  False  True

In [ ]:
df=pd.DataFrame({
    "a":[1,2,3,4]})
df.insert(1,"name",df["a"])
df.insert(2,"name2",["a","b","c","d"])
df

   a  name name2
0  1     1     a
1  2     2     b
2  3     3     c
3  4     4     d

Module 2 chapter 2 merge

In [ ]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4],
    "b":['A','B','C','D']
})
df2=pd.DataFrame({
    "a":[1,2,3,4],
    "d":['a','b','c','d']
})
pd.merge(df1,df2)

   a  b  d
0  1  A  a
1  2  B  b
2  3  C  c
3  4  D  d

In [ ]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4],
    "b":['A','B','C','D']
})
df2=pd.DataFrame({
    "a":[1,5,7,3],
    "c":['a','b','c','d']
})
pd.merge(df1,df2,on="a", how='outer', indicator=True)

   a    b    c      _merge
0  1    A    a        both
1  2    B  NaN   left_only
2  3    C    d        both
3  4    D  NaN   left_only
4  5  NaN    b  right_only
5  7  NaN    c  right_only

In [ ]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4],
    "b":['A','B','C','D']
})
df2=pd.DataFrame({
    "a":[1,5,7,3],
    "c":['a','b','c','d']
})
pd.merge(df1,df2,on="a", how='inner', indicator=True)

   a  b  c _merge
0  1  A  a   both
1  3  C  d   both

In [ ]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4],
    "b":['A','B','C','D']
})
df2=pd.DataFrame({
    "a":[1,5,7,3],
    "c":['a','b','c','d']
})
pd.merge(df1,df2,on="a", how='left',indicator=True)

   a  b    c     _merge
0  1  A    a       both
1  2  B  NaN  left_only
2  3  C    d       both
3  4  D  NaN  left_only

In [ ]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4],
    "b":['A','B','C','D']
})
df2=pd.DataFrame({
    "a":[1,5,7,3],
    "c":['a','b','c','d']
})
pd.merge(df1,df2,on="a", how='right',indicator=True)

   a    b  c      _merge
0  1    A  a        both
1  5  NaN  b  right_only
2  7  NaN  c  right_only
3  3    C  d        both

index

In [ ]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":['A','B','C','D','E']
})
df2=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":['a','b','c','d','e']
})
pd.merge(df1,df2,left_index=True,right_index=True)

   a_x b_x  a_y b_y
0    1   A    1   a
1    2   B    2   b
2    3   C    3   c
3    4   D    4   d
4    5   E    5   e

suffix

In [ ]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":['A','B','C','D','E']
})
df2=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":['a','b','c','d','e']
})
pd.merge(df1,df2,left_index=True,right_index=True,suffixes=('_id','_name'))

   a_id b_id  a_name b_name
0     1    A       1      a
1     2    B       2      b
2     3    C       3      c
3     4    D       4      d
4     5    E       5      e

join

In [3]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":['A','B','C','D','E']
})
df2=pd.DataFrame({
    "d":[1,2,3,4,5],
    "c":['a','b','c','d','e']
})
df1.join(df2)

   a  b  d  c
0  1  A  1  a
1  2  B  2  b
2  3  C  3  c
3  4  D  4  d
4  5  E  5  e

In [8]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4],
    "b":['A','B','C','D']
})
df2=pd.DataFrame({
    "d":[1,2,3,4],
    "c":['a','b','c','d']
})
df2.join(df1)

   d  c  a  b
0  1  a  1  A
1  2  b  2  B
2  3  c  3  C
3  4  d  4  D

index in join

In [16]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":['A','B','C','D','E']
},
index=['a','b',2,'d','e'])
df2=pd.DataFrame({
    "d":[1,2,3,4,5],
    "c":['a','b','c','d','e']
})
df1.join(df2)

   a  b    d    c
a  1  A  NaN  NaN
b  2  B  NaN  NaN
2  3  C  3.0    c
d  4  D  NaN  NaN
e  5  E  NaN  NaN

In [17]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":['A','B','C','D','E']
},
index=['a','b',2,'d','e'])
df2=pd.DataFrame({
    "d":[1,2,3,4,5],
    "c":['a','b','c','d','e']
},
index=['d','b',2,'a','e']                 )
df1.join(df2)

   a  b  d  c
a  1  A  4  d
b  2  B  2  b
2  3  C  3  c
d  4  D  1  a
e  5  E  5  e

In [27]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":[10,20,30,40,50]
},
index=['a','b','c','d','e'])
df2=pd.DataFrame({
    "c":['a','b','c'],
    "d":['A','B','C']
},
index=['a','b','c']                 )
df1.join(df2, how = 'inner')

   a   b  c  d
a  1  10  a  A
b  2  20  b  B
c  3  30  c  C

In [28]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":[10,20,30,40,50]
},
index=['a','b','c','d','e'])
df2=pd.DataFrame({
    "c":['a','b','c'],
    "d":['A','B','C']
},
index=['a','b','c']                 )
df1.join(df2, how = 'outer')

   a   b    c    d
a  1  10    a    A
b  2  20    b    B
c  3  30    c    C
d  4  40  NaN  NaN
e  5  50  NaN  NaN

In [29]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":[10,20,30,40,50]
},
index=['a','b','c','d','e'])
df2=pd.DataFrame({
    "c":['a','b','c'],
    "d":['A','B','C']
},
index=['a','b','c']                 )
df1.join(df2, how = 'left')

   a   b    c    d
a  1  10    a    A
b  2  20    b    B
c  3  30    c    C
d  4  40  NaN  NaN
e  5  50  NaN  NaN

In [30]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":[10,20,30,40,50]
},
index=['a','b','c','d','e'])
df2=pd.DataFrame({
    "c":['a','b','c'],
    "d":['A','B','C']
},
index=['a','b','c']                 )
df1.join(df2, how = 'right')

   a   b  c  d
a  1  10  a  A
b  2  20  b  B
c  3  30  c  C

In [32]:
import pandas as pd
df1=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":['A','B','C','D','E']
})
df2=pd.DataFrame({
    "a":[1,2,3,4,5],
    "b":['a','b','c','d','e']
})
df1.join(df2,lsuffix='_df1',rsuffix='_df2')

   a_df1 b_df1  a_df2 b_df2
0      1     A      1     a
1      2     B      2     b
2      3     C      3     c
3      4     D      4     d
4      5     E      5     e